# Generated by Django 3.0 on 2024-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/sachin.jpg', upload_to='profile_pics'),
        ),
    ]
